env:
  global:
    - secure: zx1x7wPTlx2CNtrZoHKG8V2lrRGb7k9db8OezecxJLD3UD9HzWCmNl/MSCzAli2ljUu3NnOF8X+wq3FSLpGhc6o91tJ3ctkmgeNm0QKs9/kx8pnUgQ5/pmWaoNny9O3t3dIw9Ojb6IeQP761XdrPEEr47gZvKI1HZf6ZZSTkRJmCC953O/dNMAdpbIoD6YGKRPIYs0LvBdPGfXP69YkMtvTPqdz46WKPmPFZXEF9OK+nOnm14IlpKVzMYBc7ERr8h/nK9aG+QbEja0qEAeHyIAmAA0/l8G1ahyrqyKlCAd57EesC7zg+Hb4eqWGtcxLmLYIlkWow0RrCGxVi++fd3m/wPhMV8WAGSdHG6Udg65CoedPKQBK4W13RPo8XBy5Ap7aN8LMjEj7kpuRBERwCrjEqSXKGNPd/9kzO+LMP/m81b/Yn5a6Ww1hRjhp4uOhrVNUxlShmjYQ/TvLaMx+X9cWmtW/mKju/FHPi0OX0Mfc0YlIVtnezpyM4SvgU6GkQtOqRFNzsGGO26iMoch+OPhNtACCvUFD+rBF6dPS6jKM/yeE4I2M10IpmRAI7hTOsWKuPgFcV0b0ptQFvKt8nfSRsJZ2Qdovl7x7/wbI1T7BfURXX70NnoYhJTtttW2/yzKvoLvITEGbkKIigYPHgA1bQYacPDryWX7q2r12M+yU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master
    - TZ:       Africa/Johannesburg
    - PYFUNCEBLE_CONFIG_DIR: ${TRAVIS_BUILD_DIR}/.dev-tools/
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

dist: bionic

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install domain2idna
  - pip3 install PyFunceble-dev
  - pip3 install ultimate-hosts-blacklist-whitelist

script:
  - bash .dev-tools/pre-deploy.sh

notifications:
  on_success:   change
  on_failure:   always
