language: php
env:
  global:
    - secure: i7vGRxrS4RgR6fIj262f/r2dTPV3cUWSvS7eAo1XotrmRH314DCcxW29kULHwV+uHbN1zpkr+yK5C2ECEAXFeEBxa3ANJ7A37Ypu+z09ihGWCNHL8LWbw2CwLDtj20qNCAhlVkv6pFZ5J8dYbofinxjPer3GzwhdMyCC5KlLfsKPgF1NJL0O4y9BqEICF0uh6Bt2rN3S5nIfsljzY0mWnvwrFr3O0330gMf2ijN37HvjuHS0TvQVKB/CK3iVaI9oivpudu2nH8lXbsPzmSCrW2h2EFoqOTBkVcR/9T7BqnpMq/+P7KhvJaal35ts2ySGFxN0GY0ZVio8XVwGUJj9UJ/H0XJGVx1ZengsP0UzTf6GNxQ8TJ+Kft5erj52MktwCMytkHTnDZXjTw+fWRwsYhKlQSY7IUPe5mFW/htzfTLdCtgUxQvrg/eS1zgcSStsq4NsM61nntUuLa3Q42TRJ4pD2gjw/eHLeZHjwZfghR0J9pMslbcCa+NwaPzwVH+RlEAsXrdKIgR07gDDa/2V4nVi0f6pj3NE4HXiuyzRbZqORpdHGA8Drf1myDZh+XOjk8EH/qqzRqFf5t4+qf6uSLpBnd8R8aEDrYp1zAx5izmoWHpXk8zCS05Gk9QAfCk4h9K2szpp/FN6Mlgz1swqyV35HBdSVzzbiucVVHReidc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master

dist: trusty
sudo: required
matrix:
  fast_finish: true

cache:
  - apt

script:
  - bash travisCI/pre-deploy.sh

before_deploy:
  - bash travisCI/deploy-package.sh

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - "hacked-malware-websites.txt"
  skip_cleanup: true
  on:
    repo: mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites
    tags: false
    branches:
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
    branches:
       only:
         - "master"
notifications:
  email: false